# Generated by Django 6.0.5 on 2026-05-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='students/')),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12, unique=True)),
                ('class_roll', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('p_o', models.CharField(max_length=100)),
                ('p_s', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
