# Generated by Django 6.0.5 on 2026-05-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
